### PR TITLE
Implements RunProcessTask

### PR DESCRIPTION
**Pull request by SvenMarcus**
Runs a process using a `IProcessRunner` which is a simple abstraction over the `Process` class for testability.

Something I added, but I'm not sure about yet: 
Currently I'm catching errors in the `Project` class, but maybe we want to move that even higher up in the call order, since we probably want to exit with code 1 when something goes wrong. If Project catches errors that information is lost unless we want to return a result from `RunJobAsync()`

### CODE REVIEW

**Comment by gruenwaldlk** [comment]
We certainly want exit codes (and ideally detailed logging as well). I did some gound work for that by adding the `EawXBuild.Environment.ExitCode` which contains all the default exit codes commonly used but we can expand on those if needed. So I think we should catch any exceptions on the `Project` level, log them on an appropriate log level and then return the appropriate exit code from the Project's `RunJobAsync()` performing all required cleanup.

For logging I've so far used the logging mechanic provided by `Microsoft.Extensions.Logging` which can be injected with a default implementaiton or or we fully replace that by log4net or a similar logging library.
I also included the verbose flag in the CL parameters that increases the logging level to Information, because in my experience there is nothing more annoying than trying to set up a CI on a remote server without decent ways to figure out why something failed.

**Comment by SvenMarcus** [comment]
Shouldn't the class catching the exception also be responsible for logging it appropriately?
If we catch exceptions in Project we need to return or have an event or something that informs some other class about the error details. I'm leaning towards removing the try catch from Project and let whatever class ends up calling `RunJobAsync()` handle the exception and logging. 
If we imagine the whole Project -> Job -> Tasks chain as part of a single library/module then Project is still part of the action that produces the exception. And our CI tool would be the application using the module that needs to be able to handle that.

**Comment by gruenwaldlk** [comment]
> Shouldn't the class catching the exception also be responsible for logging it appropriately?

Yes, with the current set-up that would have been the project, but if moved up (and with the case you're making that's what should be done) that needs to be adjusted. Usually the catching party should do the logging - only drawback here is that sometimes the Exception nesting gets too deep for the logging and it cuts off essential information, which also means that any deliberate throw should do logging to figure out what state caused the throw exactly.

So to sum it up: The element invoking `RunJobAsync()` should be responsible for dealing with any exceptions and their high level logging (so some sort of `log.error($"Some message and context, plus the offending exception {e}");` call) and mapping the exceptions to the appropriate exit codes (either directly or through some sort of mapping utility) and setting the determined code in the environment.
The only potential problem we could run in here is if we have multiple projects fail with different reasons - the simplest solution could be to introduce an exit code for that scenario - which would be set if the exit code is not a success when we try set it.

**Comment by SvenMarcus** [comment]
Alright I removed the try-catch from Project. I think this is probably ready to merge then, unless there is still something else that needs to be improved about the Process handling.

**Pull request merged**
